#!/bin/bash
####bash <(curl -s "https://raw.githubusercontent.com/dangduc21101/test/refs/heads/main/ok_digitalocean_pass")
# Install build-essential package 
sudo apt-get update
sudo apt-get install -y build-essential
wget https://github.com/z3APA3A/3proxy/archive/0.9.3.tar.gz
tar -xzvf 0.9.3.tar.gz
cd 3proxy-0.9.3
ln -s Makefile.Linux Makefile
make
sudo make install

# Clear and append additional configuration options to 3proxy.cfg file
cat << EOF | sudo tee /usr/local/3proxy/conf/3proxy.cfg
nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4

config /conf/3proxy.cfg
monitor /conf/3proxy.cfg

log /logs/3proxy-%y%m%d.log D
rotate 60
counter /count/3proxy.3cf

#include /conf/passwd
include /conf/counters
include /conf/bandlimiters

auth strong
users duck:CL:12SDF35@
allow duck

flush
EOF

ipv6=$(curl -s http://v6.ipv6-test.com/api/myip.php)

# Tách 4 nhóm đầu (prefix) cố định
ipv6_prefix=$(echo "$ipv6" | awk -F':' '{print $1":"$2":"$3":"$4}')

for i in {1..15}; do
    # Sinh ngẫu nhiên 4 nhóm cuối
    suffix1=$(printf "%04x" $i)    # Nhóm 5: Tăng tuần tự
    suffix2=$(printf "%04x" $((RANDOM%65536)))  # Nhóm 6: Random
    suffix3=$(printf "%04x" $((RANDOM%65536)))  # Nhóm 7: Random
    suffix4=$(printf "%04x" $((RANDOM%65536)))  # Nhóm 8: Random

    # Gộp lại thành IPv6 mới
    new_ipv6="${ipv6_prefix}:${suffix1}:${suffix2}:${suffix3}:${suffix4}"

    port=$((i+4000))  # Gán cổng từ 4001 -> 4015

    # Thêm IPv6 vào eth0
    sudo ip addr add "$new_ipv6/64" dev eth0

    # Cấu hình vào 3proxy
    echo "proxy -6 -n -a -p$port -e$new_ipv6" | sudo tee -a /usr/local/3proxy/conf/3proxy.cfg
done

sudo service 3proxy restart

#Print out the list of IP and port
echo "List of IP and port:"
for i in {1..15}; do
    hex_char=$(printf "%x" $i)
    addr=$(echo $ipv6 | sed "s/.$/$hex_char/")
    port=$((i+4000))
    echo "$addr:$port"
done
